config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  devise_for :users
  resources :exams do
    resources :questions, only: [:index, :new, :create]
  end

  resources :questions, only: [:show, :edit, :update, :destroy] do
    resources :answers, only: [:index, :new, :create]
  end
  resources :answers, only: [:show, :edit, :update, :destroy]

  get 'public/index'
  get 'public/admin_login'
  post 'public/admin_login', to: 'public#create_admin_session'

  root to: "public#index"
  get 'public/practice/:question_id', to: 'public#practice', as: :public_practice
  get 'public/test_500', to: 'public#test_500'
  get 'public/summary/:exam_id', to: 'public#summary', as: :public_summary
  post 'public/answer/:question_id', to: 'public#answer', as: :public_answer
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :exam
  has_many :user_answers, dependent: :destroy # must be before answers to accomodate foreign key constraints
  has_many :user_results, dependent: :destroy # must be before answers to accomodate foreign key constraints
  has_many :answers, dependent: :destroy
  validates_presence_of :prompt
  validates_presence_of :source
  validates_uniqueness_of :prompt

  def to_s
    "#{prompt}:\n\t#{answers.map(&:to_s).join("\n\t")}\n\t#{explanation}"
  end

  def next_question
    exam.questions.where("id > ?", id).order(id: :asc).first
  end

  def correct_answers
    answers.where(correct: true)
  end

  def is_multi_select?
    correct_answers.count > 1
  end

  def answered?(user)
    user_answers.where(user_id: user.id).count > 0
  end

  def correct_answers?(given_answers)
    correct_answers.map(&:id).sort == given_answers.map(&:id).sort
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]
  before_action :set_exam, only: [:index, :new, :create]

  # GET /questions or /questions.json
  def index
    @questions = @exam.questions.all
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = @exam.questions.build
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = @exam.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to exam_questions_url(@question.exam), notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    def set_exam
      @exam = Exam.find(params[:exam_id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:prompt, :source, :explanation, :exam_id)
    end
end

app/views/questions/_form.html.erb
<%= form_with(model: [@exam, question]) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :prompt %>
    <%= form.text_area :prompt, cols: 80, rows: 10 %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_area :source, cols: 50, rows: 2 %>
  </div>

  <div class="field">
    <%= form.label :explanation %>
    <%= form.text_area :explanation, cols: 80, rows: 10 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', exam_questions_path(@question.exam) %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Prompt</th>
      <th>Source</th>
      <th>Explanation</th>
      <th>Exam</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.prompt %></td>
        <td><%= question.source %></td>
        <td><%= question.explanation %></td>
        <td><%= question.exam_id %></td>
        <td><%= link_to 'Answers', question_answers_path(question) %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_exam_question_path(@exam) %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', exam_questions_path(@exam) %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prompt:</strong>
  <%= @question.prompt %>
</p>

<p>
  <strong>Source:</strong>
  <%= @question.source %>
</p>

<p>
  <strong>Explanation:</strong>
  <%= @question.explanation %>
</p>

<p>
  <strong>Exam:</strong>
  <%= @question.exam.title %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', exam_questions_path(@question.exam) %>