config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  devise_for :users
  resources :exams do
    resources :questions, only: [:index, :new, :create]
  end

  resources :questions, only: [:show, :edit, :update, :destroy] do
    resources :answers, only: [:index, :new, :create]
  end
  resources :answers, only: [:show, :edit, :update, :destroy]

  get 'public/index'
  get 'public/admin_login'
  post 'public/admin_login', to: 'public#create_admin_session'

  root to: "public#index"
  get 'public/practice/:question_id', to: 'public#practice', as: :public_practice
  get 'public/test_500', to: 'public#test_500'
  get 'public/summary/:exam_id', to: 'public#summary', as: :public_summary
  post 'public/answer/:question_id', to: 'public#answer', as: :public_answer
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  has_many :user_answers
  validates_presence_of :prompt

  def to_s
      " #{correct? ? "*" : " "} : #{self.prompt}"
  end

  def selected_by?(user)
    user_answers.where(user_id: user.id).count > 0
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: %i[ show edit update destroy ]
  before_action :set_question, only: [:index, :new, :create]

  # GET /answers or /answers.json
  def index
    @answers = @question.answers.all
  end

  # GET /answers/1 or /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = @question.answers.build
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers or /answers.json
  def create
    @answer = @question.answers.build(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: "Answer was successfully created." }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1 or /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: "Answer was successfully updated." }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1 or /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to question_answers_url(@answer.question), notice: "Answer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    def set_question
      @question = Question.find(params[:question_id])
    end

    # Only allow a list of trusted parameters through.
    def answer_params
      params.require(:answer).permit(:prompt, :correct, :question_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: [@question, answer]) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :prompt %>
    <%= form.text_area :prompt, cols: 80, rows: 10 %>
  </div>

  <div class="field">
    <%= form.label :correct %>
    <%= form.check_box :correct %>
  </div>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.text_field :question_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', question_answers_path(@answer.question) %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<p><%= @question.prompt %></p>

<table>
  <thead>
    <tr>
      <th>Prompt</th>
      <th>Correct</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.prompt %></td>
        <td><%= answer.correct %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_question_answer_path(@question) %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', question_answers_path(@question) %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prompt:</strong>
  <%= @answer.prompt %>
</p>

<p>
  <strong>Correct:</strong>
  <%= @answer.correct %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', question_answers_path(@answer.question) %>