config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  devise_for :users
  resources :exams do
    resources :questions, only: [:index, :new, :create]
  end

  resources :questions, only: [:show, :edit, :update, :destroy] do
    resources :answers, only: [:index, :new, :create]
  end
  resources :answers, only: [:show, :edit, :update, :destroy]

  get 'public/index'
  get 'public/admin_login'
  post 'public/admin_login', to: 'public#create_admin_session'

  root to: "public#index"
  get 'public/practice/:question_id', to: 'public#practice', as: :public_practice
  get 'public/test_500', to: 'public#test_500'
  get 'public/summary/:exam_id', to: 'public#summary', as: :public_summary
  post 'public/answer/:question_id', to: 'public#answer', as: :public_answer
end

app/models/exam.rb
class Exam < ApplicationRecord
  validates_presence_of :title
  has_many :questions, dependent: :destroy
  has_many :user_results, dependent: :destroy

  def completed_by_user_count
    raw_query = <<-SQL
      SELECT
        UR.user_id,
        count(*) as answered_questions
      FROM user_results UR
      WHERE UR.exam_id = :exam_id
      GROUP BY UR.user_id
    SQL

    query = Exam.sanitize_sql_for_assignment([raw_query, {exam_id: id}])

    question_count = questions.count
    ActiveRecord::Base.connection.execute(query).inject(0) do |acc, row|
      if row["answered_questions"] == question_count
        acc + 1
      else
        acc
      end
    end
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: %i[ show edit update destroy ]

  # GET /exams or /exams.json
  def index
    @exams = Exam.order(created_at: :desc).all
  end

  # GET /exams/1 or /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams or /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: "Exam was successfully created." }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1 or /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: "Exam was successfully updated." }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1 or /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: "Exam was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exam_params
      params.require(:exam).permit(:title, :open)
    end
end

app/views/exams/_form.html.erb
<%= form_with(model: exam) do |form| %>
  <% if exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
        <% exam.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :open %>
    <%= form.check_box :open %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<h1>Editing Exam</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

app/views/exams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exams</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Open</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= exam.title %></td>
        <td><%= exam.open %></td>
        <td><%= link_to 'Review', public_summary_path(exam_id: exam.id) %></td>
        <td><%= link_to 'Questions', exam_questions_path(exam) %></td>
        <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
        <td><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exam', new_exam_path %>

app/views/exams/new.html.erb
<h1>New Exam</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Back', exams_path %>

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @exam.title %>
</p>

<p>
  <strong>Open:</strong>
  <%= @exam.open %>
</p>

<%= link_to 'Edit', edit_exam_path(@exam) %> |
<%= link_to 'Back', exams_path %>