config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  devise_for :users
  resources :exams do
    resources :questions, only: [:index, :new, :create]
  end

  resources :questions, only: [:show, :edit, :update, :destroy] do
    resources :answers, only: [:index, :new, :create]
  end
  resources :answers, only: [:show, :edit, :update, :destroy]

  get 'public/index'
  get 'public/admin_login'
  post 'public/admin_login', to: 'public#create_admin_session'

  root to: "public#index"
  get 'public/practice/:question_id', to: 'public#practice', as: :public_practice
  get 'public/test_500', to: 'public#test_500'
  get 'public/summary/:exam_id', to: 'public#summary', as: :public_summary
  post 'public/answer/:question_id', to: 'public#answer', as: :public_answer
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KnightShift</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('helmet.png') %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta property="og:title" content="Home" />
    <meta property="og:site_name" content="KnightShift" />
    <meta property="og:description" content="DePaul MENP practice questions" />
    <meta property="og:image" content="<%= image_url('helmet.png') %>" />
    <meta name="turbolinks-cache-control" content="no-cache">
  </head>

  <body>
    <div id="header">
      <%= link_to(image_tag("trumpet.png", id: "banner-right"), "/")  %>
      <%= link_to(image_tag("banner.png", id: "banner-left"), "/")  %>
      <%= link_to("KnightShift", "/", id: "banner-text", class: "knightshift-font") %>


      <% if signed_in? %>
        <% if current_user.admin? %>
          <br/>
          <%= link_to("Logout", destroy_user_session_path, method: :delete) %>
          |
          <%= link_to("Exams", exams_url) %>
          |
          <%= link_to("Public", public_index_url) %>
          |
          <%= link_to("Admin", admin_index_url) %>
        <% end %>
      <% end %>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </body>
</html>